{{- include "adp-helm-library.container-secret" (list . "ffc-demo-02.container-secret") -}}
{{- define "ffc-demo-02.container-secret" -}}
stringData:
  {{- if .Values.appInsights.connectionString }}
  APPINSIGHTS_CONNECTIONSTRING: {{ quote .Values.appInsights.connectionString }}
  {{- end }}
{{- end -}}
